# SQLite version 3.x
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'
#
default: &default
  host: 192.168.0.178
  port: 1521
  adapter: oracle_enhanced
  pool: 5
  timeout: 5000
  username: root
  password: root

development:
  <<: *default
  database: fushang318
